[project]
name = "dump-truck"
version = "0.1.0"
description = "This is dumping ground!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "langchain>=1.1.0",
    "langgraph>=1.0.4",
    "pydantic>=2.12.4",
]
